//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saving.Applications.cmd.w_sheet_cmd_ucf_invtadjtype_ctrl {
    
    
    public partial class w_sheet_cmd_ucf_invtadjtype {
        
        /// <summary>
        /// dsMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.cmd.w_sheet_cmd_ucf_invtadjtype_ctrl.DsMain dsMain;
        
        /// <summary>
        /// dsList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.cmd.w_sheet_cmd_ucf_invtadjtype_ctrl.DsList dsList;
        
        /// <summary>
        /// dsList2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.cmd.w_sheet_cmd_ucf_invtadjtype_ctrl.DsList2 dsList2;
        
        /// <summary>
        /// Hdadd_status control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField Hdadd_status;
    }
}
