//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saving.Applications.assist.ws_wheet_as_request_ctrl {
    
    
    public partial class ws_wheet_as_request {
        
        /// <summary>
        /// dsMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.assist.ws_wheet_as_request_ctrl.DsMain dsMain;
        
        /// <summary>
        /// dsAssisttype control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.assist.ws_wheet_as_request_ctrl.DsAssisttype dsAssisttype;
        
        /// <summary>
        /// dsEducation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.assist.ws_wheet_as_request_ctrl.DsEducation dsEducation;
        
        /// <summary>
        /// dsDecease control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.assist.ws_wheet_as_request_ctrl.DsDecease dsDecease;
        
        /// <summary>
        /// dsFamilydecease control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.assist.ws_wheet_as_request_ctrl.DsFamilydecease dsFamilydecease;
        
        /// <summary>
        /// dsDisaster control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.assist.ws_wheet_as_request_ctrl.DsDisaster dsDisaster;
        
        /// <summary>
        /// dsPatronize control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.assist.ws_wheet_as_request_ctrl.DsPatronize dsPatronize;
        
        /// <summary>
        /// dsGain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.assist.ws_wheet_as_request_ctrl.DsGain dsGain;
        
        /// <summary>
        /// dsAmount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.assist.ws_wheet_as_request_ctrl.DsAmount dsAmount;
        
        /// <summary>
        /// dsList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Saving.Applications.assist.ws_wheet_as_request_ctrl.DsList dsList;
        
        /// <summary>
        /// hdTabIndex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdTabIndex;
        
        /// <summary>
        /// hdSaveChk_GPA control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdSaveChk_GPA;
        
        /// <summary>
        /// hdInertRow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdInertRow;
        
        /// <summary>
        /// hdCalDay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdCalDay;
        
        /// <summary>
        /// hdActMemno control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdActMemno;
        
        /// <summary>
        /// hdCheckDsAmount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdCheckDsAmount;
    }
}
