//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saving.Applications.keeping.ws_kp_opr_recieve_store_other_ctrl
{


    public partial class ws_kp_opr_recieve_store_other
    {
    }
}
