//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saving.Applications.mbshr.ws_mbshr_member_detail_ctrl
{


    public partial class ws_mbshr_member_detail
    {
    }
}
